### PR TITLE
Big refactoring

### PR DESCRIPTION
**Pull request by mateuszchudyk**
What do you think about that?
- All backends are placed in backends subdir, each of them is an explicit specialization of template Backend<CPUType, Integer>
- BackendInfo template extracts info about CPUType and Integer from backend
- Int8/Int8Shift/Int16 defines expected interface to a backend that is used by them.

### CODE REVIEW

**Comment by kpu** [comment]
Does backend mean multiply?  Might be cleaner to call it that (though I realize that's the namesake of the package).

**Comment by kpu** [comment]
I'd also like to see the macros replaced by multiple inclusion but that's another refactor.  

Are we just creating virtual functions all over again?

**Comment by mateuszchudyk** [comment]
"Does backend mean multiply?"
Not exactly, because they do also preparing matrix, etc.

No, we still use function pointers. The difference is that I extracted these pointers to a separate structure (BackendInterface) to make binding easier and more automatic.

**Comment by XapaJIaMnu** [comment]
Guys, I have been working on integrating intgemm back into marian. Can we focus on the functionality necessary before refactoring, because once we get our code into master, we no longer need to work out of tree.

We need separate quantizer and tile functions, as well as a strategy for dealing with non multiple of 64 matrices for the self attention.

**Pull request closed without merging**
