### PR TITLE
Rename config file

### PR DESCRIPTION
**Pull request by mateuszchudyk**

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
@mateuszchudyk , i can't compile marian with the latest master:
```
[ 75%] Building CXX object src/CMakeFiles/marian.dir/tensors/cpu/prod.cpp.o
In file included from /home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/bias.h:3,
                 from /home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/prod.cpp:18:
/home/dheart/uni_stuff/postdoc/marian-dev/src/3rd_party/intgemm/intrinsics.h:3:10: fatal error: intgemm_config.h: No such file or directory
    3 | #include "intgemm_config.h"
      |          ^~~~~~~~~~~~~~~~~~
```

**Comment by mateuszchudyk** [comment]
Did you try rebuild?

**Comment by XapaJIaMnu** [comment]
I did a make clean. MAybe i should rerun cmake

**Comment by XapaJIaMnu** [comment]
Ok, more progress, but now I can't find the WriteC kernels:
```
home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/integer.h:155:96: error: ‘intgemm::callbacks’ has not been declared
  155 |     intgemm::Int8::PrepareBiasFor8(1, (const int8_t *)b->data(), 1, rows(b), cols(b), intgemm::callbacks::UnquantizeAndAddBiasAndWrite(unquant_mult, bias->data(), val_->data()));
      |                                                                                                ^~~~~~~~~
/home/dheart/uni_stuff/postdoc/marian-dev/src/graph/chainable.h:10:28: note: in definition of macro ‘NodeOp’
   10 | #define NodeOp(op) [=]() { op; }
      |                            ^~
/home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/integer.h: In lambda function:
/home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/integer.h:183:96: error: ‘intgemm::callbacks’ has not been declared
  183 |     intgemm::Int8::PrepareBiasFor8(1, (const int8_t *)b->data(), 1, rows(b), cols(b), intgemm::callbacks::UnquantizeAndWrite(unquant_mult, val_->data()));
      |                                                                                                ^~~~~~~~~
/home/dheart/uni_stuff/postdoc/marian-dev/src/graph/chainable.h:10:28: note: in definition of macro ‘NodeOp’
   10 | #define NodeOp(op) [=]() { op; }
      |                            ^~
/home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/integer.h: In lambda function:
/home/dheart/uni_stuff/postdoc/marian-dev/src/tensors/cpu/integer.h:312:22: error: ‘intgemm::callbacks’ has not been declared
  312 |       using intgemm::callbacks::UnquantizeAndWrite;
```

**Pull request merged**
